cashier/backoffice/cashier/urls.py
from django.urls import path
from .import views
app_name = "cashier"

urlpatterns = [
    path("", views.CashierView, name="index"),
]

cashier/backoffice/urls.py
from django.urls import path, include
from . import views
app_name = "backoffice"
urlpatterns = [
    path('', views.DashboardView.as_view(), name='index'),
    path("product/", include("cashier.backoffice.product.urls")),
    path("transactions/", include("cashier.backoffice.transactions.urls")),
    path("cashier/", include("cashier.backoffice.cashier.urls")),
    path("users/", include("cashier.backoffice.users.urls")),
]

cashier/backoffice/users/urls.py
from django.urls import path
from . import views
app_name = "users"
urlpatterns = [
    path("", views.UserListView.as_view(), name="index"),
    path("edit/<pk>", views.UserEditView.as_view(), name="edit"),
    path("delete/<pk>", views.UserDeleteView.as_view(), name="delete"),
]

cashier/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("cashier.website.urls")),
    path("backoffice/", include("cashier.backoffice.urls"))
]

cashier/website/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

# from .views import
from cashier.apps.accounts.views import MyPasswordChangeView
from cashier.website.accounts.views import LogoutView, LoginView

app_name = "accounts"

urlpatterns = [
    path("change-password", MyPasswordChangeView.as_view(), name="change_password"),
    path("set-password", MyPasswordChangeView.as_view(), name="set_password"),
    path("reset-password", MyPasswordChangeView.as_view(), name="reset_password"),
    path('auth-logout/', TemplateView.as_view(template_name="account/logout-success.html"), name='pages-logout'),
    path('auth-lockscreen/', TemplateView.as_view(template_name="account/lock-screen.html"), name='pages-lockscreen'),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("register", LogoutView.as_view(), name="register"),
]

cashier/backoffice/cashier/views.py
from django.shortcuts import render

# Create your views here.


def CashierView(request):
    context = {}
    return render(request, 'backoffice/cashier/index.html', context)

cashier/backoffice/product/category/views.py
from django.core.paginator import Paginator

from cashier.apps.product.forms import ProductCategoryForm
from cashier.apps.product.models import Category
from cashier.backoffice.views import BaseListView, BaseDeleteView, BaseCreateFormView, BaseFormView


class ProductCategoryListView(BaseListView):
    model = Category
    paginator_class = Paginator
    paginate_by = 20
    template_name = "backoffice/product/category_list.html"


class ProductCategoryCreateView(BaseCreateFormView):
    form_class = ProductCategoryForm
    template_name = "backoffice/product/form.html"


class ProductCategoryEditView(BaseFormView):
    form_class = ProductCategoryForm
    model = Category
    template_name = "backoffice/product/form.html"


class ProductCategoryDeleteView(BaseDeleteView):
    model = Category

cashier/backoffice/product/views.py
from django.core.paginator import Paginator

from cashier.apps.product.forms import ProductItemForm
from cashier.apps.product.models import Item
from cashier.backoffice.views import BaseListView, BaseCreateFormView, BaseFormView, BaseDeleteView, BaseDetailView


class ProductListView(BaseListView):
    model = Item
    paginator_class = Paginator
    paginate_by = 10
    template_name = "backoffice/product/index.html"


class ProductCreateView(BaseCreateFormView):
    template_name = "backoffice/product/form.html"
    form_class = ProductItemForm

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(user=self.request.user, **self.get_form_kwargs())


class ProductEditView(BaseFormView):
    form_class = ProductItemForm
    model = Item
    template_name = "backoffice/product/form.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(instance=self.get_object(), user=self.request.user, **self.get_form_kwargs())


class ProductDeleteView(BaseDeleteView):
    model = Item


class ProductDetailView(BaseDetailView):
    model = Item

cashier/backoffice/transactions/views.py
from django.core.paginator import Paginator

from cashier.apps.sale.models import Order
from cashier.backoffice.views import BaseListView, BaseDetailView


class TransactionListView(BaseListView):
    model = Order
    paginator_class = Paginator
    paginate_by = 20
    template_name = "backoffice/sale/index.html"


class TransactionDetailView(BaseDetailView):
    model = Order

cashier/backoffice/users/views.py
from cashier.apps.accounts.forms import UserForm
from cashier.apps.accounts.models import User
from cashier.backoffice.views import BaseListView, BaseCreateFormView, BaseFormView, BaseDeleteView


class UserListView(BaseListView):
    model = User
    template_name = "backoffice/users/index.html"


class UserCreateView(BaseCreateFormView):
    form_class = UserForm


class UserEditView(BaseFormView):
    form_class = UserForm


class UserDeleteView(BaseDeleteView):
    model = User

cashier/backoffice/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin

from cashier.backoffice.mixins import ContextTitleMixin


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        context = {}
        context['heading'] = "Dashboard"
        context['pageview'] = "Dashboards"
        return render(request, 'backoffice/dashboard.html', context)


@method_decorator(login_required, name='dispatch')
class BaseListView(ContextTitleMixin, ListView):
    model = None
    title_page = 'List'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(name__icontains=query)
        else:
            object_list = self.model.objects.all()
        return object_list

    def get_context_data(self, **kwargs):
        page_number = self.request.GET.get('page', 1)
        context = super().get_context_data(**kwargs)
        page_range = context['page_obj'].paginator.get_elided_page_range(number=page_number)
        context['page_range'] = page_range
        return context


class BaseFormView(ContextTitleMixin, FormMixin, DetailView):
    template_name = "backoffice/form.html"
    title_page = "Edit Form"
    success_url = "/backoffice"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = self.get_object()
        if form.is_valid():
            form.save()
            messages.success(self.request, f'Successfully {self.title_page}')
            return self.form_valid(form)
        else:
            messages.error(self.request, 'Something wrong')
            return self.form_invalid(form)

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(instance=self.get_object() or None, **self.get_form_kwargs())


@method_decorator(login_required, name='dispatch')
class BaseDeleteView(DetailView):
    model = None

    def dispatch(self, request, *args, **kwargs):
        # handle if user not same
        instance = self.get_object()
        if instance.created_by != request.user:
            messages.warning(request, "You can't delete this. You don't have permission")
            return redirect("/")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        messages.success(self.request, 'Successfully deleted one survey')
        return redirect("backoffice:plant:index")


@method_decorator(login_required, name='dispatch')
class BaseCreateFormView(CreateView, FormMixin):
    template_name = "backoffice/form.html"
    success_url = "/backoffice"


@method_decorator(login_required, name='dispatch')
class BaseDetailView(ContextTitleMixin, DetailView):
    model = None
    template_name = "backoffice/detail.html"
    title_page = "Detail"


class PagesLoginView(View):
    def get(self, request):
        return render(request, 'backoffice/login.html')

templates/backoffice/base.html
{% extends base.html %}

{% block content %}

{% endblock %}

templates/backoffice/dashboard.html
{% extends "backoffice/layouts/vertical.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-xl-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title mb-4">Monthly Earning</h4>
                    <div class="row">
                        <div class="col-sm-6">
                            <p class="text-muted">This month</p>
                            <h3>$34,252</h3>
                            <p class="text-muted"><span class="text-success me-2"> 12% <i class="mdi mdi-arrow-up"></i> </span>
                                From previous period</p>

                            <div class="mt-4">
                                <a href="javascript: void(0);" class="btn btn-primary waves-effect waves-light btn-sm">View
                                    More <i class="mdi mdi-arrow-right ms-1"></i></a>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="mt-4 mt-sm-0">
                                <div id="radialBar-chart" class="apex-charts"></div>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted mb-0">We craft digital, graphic and dimensional thinking.</p>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mini-stats-wid">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="flex-grow-1">
                                    <p class="text-muted fw-medium">Orders</p>
                                    <h4 class="mb-0">1,235</h4>
                                </div>

                                <div class="flex-shrink-0 align-self-center">
                                    <div class="mini-stat-icon avatar-sm rounded-circle bg-primary">
                                                            <span class="avatar-title">
                                                                <i class="bx bx-copy-alt font-size-24"></i>
                                                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mini-stats-wid">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="flex-grow-1">
                                    <p class="text-muted fw-medium">Revenue</p>
                                    <h4 class="mb-0">$35, 723</h4>
                                </div>

                                <div class="flex-shrink-0 align-self-center ">
                                    <div class="avatar-sm rounded-circle bg-primary mini-stat-icon">
                                                            <span class="avatar-title rounded-circle bg-primary">
                                                                <i class="bx bx-archive-in font-size-24"></i>
                                                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mini-stats-wid">
                        <div class="card-body">
                            <div class="d-flex">
                                <div class="flex-grow-1">
                                    <p class="text-muted fw-medium">Average Price</p>
                                    <h4 class="mb-0">$16.2</h4>
                                </div>

                                <div class="flex-shrink-0 align-self-center">
                                    <div class="avatar-sm rounded-circle bg-primary mini-stat-icon">
                                                            <span class="avatar-title rounded-circle bg-primary">
                                                                <i class="bx bx-purchase-tag-alt font-size-24"></i>
                                                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end row -->

            <div class="card">
                <div class="card-body">
                    <div class="d-sm-flex flex-wrap">
                        <h4 class="card-title mb-4">Email Sent</h4>
                        <div class="ms-auto">
                            <ul class="nav nav-pills">
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Week</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Month</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="#">Year</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div id="stacked-column-chart" class="apex-charts" dir="ltr"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
{% endblock %}

templates/backoffice/form.html
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="p-8 mt-6 mb-0 space-y-4 rounded-lg shadow-md border border-gray-200 bg-white">
            <label for="email" class="form-label">{{ field.label }}</label>

            <div class="mt-1">
                {% if field.field.widget.input_type == 'radio' or field.field.widget.input_type == 'checkbox' %}
                    {{ field }}
                {% else %}
                    {{ field }}
                {% endif %}
            </div>
            <span class="text-muted">{{ field.help_text }}</span>
            <span class="text-xs text-red-400">{{ field.errors }}</span>
        </div>
    {% endfor %}
    <div class="d-flex flex-wrap gap-2 mt-2">

    <a href="/backoffice" class="btn btn-danger">
        Kembali
    </a>
    <button type="submit" class="btn btn-primary">
        Submit
    </button>
    </div>
</form>

templates/backoffice/login.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}

{% block style_head %}
    <!-- Bootstrap Css -->
    <link href="{% static 'backoffice/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css"/>
    <!-- Icons Css -->
    <link href="{% static 'backoffice/css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <!-- App Css-->
    <link href="{% static 'backoffice/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css"/>
    {% block extra_css %}

    {% endblock %}
{% endblock %}

{% block script_end %}
    <!-- JAVASCRIPT -->
    <script src="{% static 'backoffice/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'backoffice/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'backoffice/libs/metismenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'backoffice/libs/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'backoffice/libs/node-waves/dist/waves.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="account-pages my-5 pt-sm-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card overflow-hidden">
                        <div class="bg-primary bg-soft">
                            <div class="row">
                                <div class="col-7">
                                    <div class="text-primary p-4">
                                        <h5 class="text-primary">Welcome Back !</h5>
                                        <p>Sign in to continue to Siberalam.</p>
                                    </div>
                                </div>
                                <div class="col-5 align-self-end">
                                    <img src="{% static 'images/profile-img.png' %}" alt="" class="img-fluid">
                                </div>
                            </div>
                        </div>
                        <div class="card-body pt-0">
                            <div class="auth-logo">
                                <a href="{% url 'backoffice:index' %}" class="auth-logo-light">
                                    <div class="avatar-md profile-user-wid mb-4">
                                            <span class="avatar-title rounded-circle bg-light">
                                                <img src="{% static 'images/logo-light.svg' %}" alt=""
                                                     class="rounded-circle" height="34">
                                            </span>
                                    </div>
                                </a>

                                <a href="{% url 'backoffice:index' %}" class="auth-logo-dark">
                                    <div class="avatar-md profile-user-wid mb-4">
                                            <span class="avatar-title rounded-circle bg-light">
                                                <img src="{% static 'images/logo.svg' %}" alt="" class="rounded-circle"
                                                     height="34">
                                            </span>
                                    </div>
                                </a>
                            </div>
                            <div class="p-2">
                                <form class="form-horizontal" action="{% url 'accounts:login' %}" method="POST"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for message in messages %}
                                        <div class="alert {{ message.tags }} mb-4 text-center" role="alert">
                                            <strong>{{ message }}</strong>
                                        </div>
                                    {% endfor %}

                                    {{ form }}

                                    <div class="mt-3 d-grid">
                                        <button class="btn btn-primary waves-effect waves-light" type="submit">Log In
                                        </button>
                                    </div>
                                    <div>

                                    </div>

                                    <div class="mt-4 text-center">
                                        <h5 class="font-size-14 mb-3">Sign in with</h5>

                                        {#                                            <ul class="list-inline">#}
                                        {#                                                <li class="list-inline-item">#}
                                        {#                                                    <a href="{% provider_login_url 'facebook' %}" class="social-list-item bg-primary text-white border-primary">#}
                                        {#                                                        <i class="mdi mdi-facebook"></i>#}
                                        {#                                                    </a>#}
                                        {#                                                </li>#}
                                        {##}
                                        {#                                                <li class="list-inline-item">#}
                                        {#                                                    <a href="{% provider_login_url 'google' %}" class="social-list-item bg-danger text-white border-danger">#}
                                        {#                                                        <i class="mdi mdi-google"></i>#}
                                        {#                                                    </a>#}
                                        {#                                                </li>#}
                                        {#                                            </ul>#}
                                    </div>

                                    <div class="mt-4 text-center">
                                        <a href="{% url 'accounts:reset_password' %}" class="text-muted"><i
                                                class="mdi mdi-lock me-1"></i> Forgot your password?</a>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                    <div class="mt-4 text-center">

                        <div>
                            <p>Don't have an account ? <a href="{% url 'accounts:register' %}"
                                                          class="fw-medium text-primary"> Signup now </a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}